server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  #type-aliases-package: com.zt.ztgeoservice.equipment.entity    # 所有Entity别名类所在包
  typeAliasesPackage: com.zt.ztgeoservice
  mapperLocations: classpath:mybatis/mapper/**/*.xml
  #配置日志
logging:
  #此处存放日志的路径
  path: src/main/resources/static/log
  config: classpath:Log4j.xml
  #指定不同目录下的日志的级别
  level:
   com.zt.ztgeoservice: DEBUG

spring:
  datasource:
    thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ztgeoservice
    username: postgres
    password: root
beetl:
  suffix: html
  #bybatis分页插件配置
  pagehelper:
    helper-dialect: postgreSQL  #数据库
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
    redis:
        host: localhost
        port: 6379
        password:
        jedis:
              pool:
                 # 连接池最大连接数（使用负值表示没有限制）
                  max-active: 8
                 # 连接池最大阻塞等待时间（使用负值表示没有限制）
                  max-wait: -1
                 # 连接池中的最大空闲连接
                  max-idle: 8
                 # 连接池中的最小空闲连接
                  min-idle: 0
                 # 连接超时时间（毫秒）
                  timeout: 5000
REDIS_KEY : student

#spring:
#      datasource:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://192.168.100:5432/ztgis
#        username: postgres
#        password: ztkj8888
#beetl:
#  suffix: html
#  #bybatis分页插件配置
#  pagehelper:
#    helper-dialect: postgreSQL  #数据库
#    reasonable: true
#    support-methods-arguments: true
#    params: count=countSql



#    spring:
#      jpa:
#        hibernate:
#          ddl-auto: update
#        properties:
#          hibernate:
#            temp:
#              use_jdbc_metadata_defaults: false
